name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libvulkan-dev vulkan-tools qt6-base-dev qt6-tools-dev qt6-svg-dev

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.16'

      - name: Configure CMake
        run: cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6

      - name: Build
        run: cmake --build build/release --config Release

      - name: Run Tests
        run: ctest --test-dir build/release --output-on-failure

  # Skip jobs for macOS and Linux since they are still in development
  skip_linux_and_macos:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - run: echo "Skipping tests for macOS and Linux as they are still in development."