name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvulkan-dev vulkan-utils

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.16'

      - name: Configure CMake
        run: cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build/release --config Release

      - name: Run Tests
        run: ctest --test-dir build/release --output-on-failure

  skip_linux_and_macos:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - run: echo "Skipping tests for macOS and Linux as they are still in development."