name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.31.0'

      - name: Configure CMake
        run: cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build/release --config Release

      - name: Run Tests
        run: ctest --test-dir build/release --output-on-failure
